using Blog.Domain.Entities.PostAggregate;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Blog.Infrastructure.Persistence.Configurations
{
    //IEntityTypeConfiguration-
    public class PostConfiguration : IEntityTypeConfiguration<Post>
    {
        //EntityTypeBuilder-
        public void Configure(EntityTypeBuilder<Post> builder)
        {
            builder.ToTable("Posts");
            builder.HasKey(x => x.PostId);

            //ValueGeneratedNever-method is used to specify that a property's value should never be generated by the database when inserting a new record.
            builder.Property(x => x.PostId).ValueGeneratedNever();
            builder.HasMany(x => x.Comments).WithOne().HasForeignKey("PostId");
        }
    }
}
